name: daily_hof2_ondemand

# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  run_1213:
    # Name the Job
    name: run_1213
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_1213
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 12,13


 

  run_1415:
    # Name the Job
    name: run_1415
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_1415
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 14,15         

            
  run_1617:
    # Name the Job
    name: run_1617
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_1617
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 16,17          
          
          
          
  run_1819:
    # Name the Job
    name: run_1819
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_1819
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 18,19           
          
          

  run_2021:
    # Name the Job
    name: run_2021
    # Set the type of machine to run on
    runs-on: ubuntu-18.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: set up python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install packages
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
          GOTAUTH: ${{ secrets.GOTAUTH}}
        run: |
          cd ../../
          pwd
          git clone https://$GOTAUTH@github.com/brokenjade3000/got_auto.git
          cd got_auto
          chmod 775 ./script/install.sh
          ./script/install.sh
          
      # Runs the Super-Linter action
      - name: run_2021
        env:
          DEFAULT_BRANCH: main
          MASTER_KEY: ${{ secrets.MASTER_KEY}}
        run: |
          pwd
          cd /home/runner/work/got_auto/src
          python --version
          python run_daily_hof.py 20
               
